api/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('items/', views.ItemView.as_view(), name='items'),
    path('items/<int:pk>', views.SingleItemView.as_view(), name='single_item'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/<int:pk>', views.SingleCartView.as_view(), name='single_cart'),
    path('download/<int:pk>', views.download_single_file, name='single_download'),
    path('download/', views.download_multiple_files, name='download'),
]

app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'app'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('items/', views.items_view, name='items'),
    path('cart/', views.cart_view, name='cart'),
    path('upload/', views.upload_view, name='upload'),
    path('upload_success/', views.upload_success_view, name='upload_success'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('', include('app.urls')),
    path('api/v1/auth/', include('djoser.urls')),
    path('api/v1/auth/', include('djoser.urls.authtoken')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <title>This is title</title>
</head>
<body>
  {% include 'partials/_header.html' %}

  <main>{% block content %} {% endblock %}</main>

  <script>
    function download(item_id, item_url) {
    var endpoint = "{% url 'api:single_download' pk=0 %}".replace("0", item_id)

    fetch(endpoint)
    .then(response => response.blob())
    .then(blob => {
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');

      link.href = url;
      filename = item_url.substring(item_url.lastIndexOf('/') + 1)
      link.download = filename;
      document.body.appendChild(link);
      
      link.click();
      
      window.URL.revokeObjectURL(url);
      document.body.removeChild(link);
    })
    .catch(error => {
      console.error('There was a problem with the fetch operation:', error);
    });
  }
  </script>
</body>
</html>

app/templates/cart.html
{% extends 'base.html' %}

{% block content %}
<br>
<button id="download-all-meme"onclick="downloadAll()">Download all memes</button>
<ul class="container">
  {% for item in data.results %}
    <li class="frame cart-item" data-id="{{ item.id }}">
      <p>{{ item.item.name }}</p>
      <img src="{{ item.item.image }}" alt=""><br>
      <div class="action-area">
        <button onclick="download('{{ item.item.id }}', '{{ item.item.image }}')">Download</button>
        <button onclick="removeFromCart('{{ item.id }}')">Remove from cart</button>
      </div>
    </li>
  {% endfor %}
</ul>

<script>
  function downloadAll() {
    var endpoint = "{% url 'api:download' %}"

    fetch(endpoint)
    .then(response => response.blob())
    .then(blob => {
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');

      link.href = url;
      filename = 'archive.zip'
      link.download = filename;
      document.body.appendChild(link);
      
      link.click();
      
      window.URL.revokeObjectURL(url);
      document.body.removeChild(link);
    })
    .catch(error => {
      console.error('There was a problem with the fetch operation:', error);
    });
  }

  function removeFromCart(item_id) {
    var endpoint = "{% url 'api:single_cart' pk=0 %}".replace("0", item_id)
    
    fetch(endpoint, {
      method: 'DELETE',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'X-CSRFToken': '{{ csrf_token }}'
      },
      body: '{}'
    })
    .then(r => r.json())
    .then(data => {
      element = document.querySelector(`.cart-item[data-id="${item_id}"]`)
      element.remove()
    })
  }
</script>
{% endblock %}

app/templates/gallery.html
{% extends 'base.html' %}

<button>Prev</button>
<button>Next</button>
<ul class="container">
  {% for item in data.results %}
    <li class="frame home-item" data-id="{{ item.id }}">
      <p>{{ item.name }}</p>
      <img src="{{ item.image }}" alt="" width="100%" height="200px"><br>
      {% block approved-status %}
      {% endblock %}
      <div class="action-area">
        <button onclick="download('{{ item.id }}', '{{ item.image }}')">Download</button>
        <button onclick="addToCart('{{ item.id }}')">Add to cart</button>
        {% block extra_actions %}
        {% endblock %}
      </div>
    </li>
  {% endfor %}
</ul>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<body>
  <h1>Hello World</h1>
</body>
{% endblock %}

app/templates/items.html
{% extends 'base.html' %}

{% block content %}

{% block filter %}
{% endblock %}

<div id="navigate-page">
  <button class="prev">Prev</button>
  <button class="next">Next</button>
</div>

<ul class="container">
  {% for item in data.results %}
    <li class="frame home-item" data-id="{{ item.id }}">
      <p>{{ item.name }}</p>
      <img src="{{ item.image }}" alt="" width="100%" height="200px"><br>
      {% block approved-status %}
      {% endblock %}
      <div class="action-area">
        <button onclick="download('{{ item.id }}', '{{ item.image }}')">Download</button>
        <button onclick="addToCart('{{ item.id }}')">Add to cart</button>
        {% block extra_actions %}
        {% endblock %}
      </div>
    </li>
  {% endfor %}
</ul>

{% block scripts %}
{% endblock %}

<script>
  function addToCart(item_id) {
    var endpoint = "{% url 'api:single_item' pk=0 %}".replace("0", item_id)
    
    fetch(endpoint, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'X-CSRFToken': '{{ csrf_token }}'
      },
      body: '{}'
    })
    .then(response => {
      if (response.status == 200) {
        alert("Add successfully")
      }
      else {
        alert("You've already added this item")
      }
    })
  }

  document.querySelector('#navigate-page .next').addEventListener('click', () => {
    urlString = '{{ data.next }}'
    if (urlString != "None") {
      url = new URL(urlString)
      queryString = url.search
    
      window.location.href = '{% url "app:items" %}' + queryString
    }
  })

  document.querySelector('#navigate-page .prev').addEventListener('click', () => {
    urlString = '{{ data.previous }}'
    if (urlString != "None") {
      url = new URL(urlString)
      queryString = url.search
    
      window.location.href = '{% url "app:items" %}' + queryString
    }
  })
</script>

{% endblock %}

app/templates/items_manager.html
{% extends 'items.html' %}

{% block filter %}
<!-- <details id="filter-bar">
  <summary>Filter</summary>
  <ul>
    <li>
      <label for="Approved">Approved</label>
      <input type="checkbox" name="Approved">
    </li>
    <li>
      <label for="Ascending">Ascending</label>
      <input type="checkbox" name="Ascending">
  </ul>
</details> -->
{% endblock %}

{% block approved-status %}
  <div id="approved-status" data-id="{{ item.id }}" class="status">Approved status: {{ item.approved }}</div>
{% endblock %}


{% block extra_actions %}
<button id="change-status" onclick="changeApproveStatus('{{ item.id }}', '{{ item.approved }}')">Change status</button><br>
<button onclick="deleteItem('{{ item.id }}')">Delete item</button>
{% endblock %}

{% block scripts %}
<script>
  function changeApproveStatus(item_id, item_status) {
    let endpoint = "{% url 'api:single_item' pk=0 %}".replace("0", item_id)
    const newStatus = (item_status == 'True') ? "False" : "True" 
    const payload = {
      'approved': newStatus
    }

    fetch(endpoint, 
    {
      method: 'PATCH',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'X-CSRFToken': '{{ csrf_token }}'
      },
      body: JSON.stringify(payload)
    })
    .then(window.location.reload())
  } 

  function deleteItem(item_id) {
    var endpoint = "{% url 'api:single_item' pk=0 %}".replace("0", item_id)
    
    fetch(endpoint, {
      method: 'DELETE',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'X-CSRFToken': '{{ csrf_token }}'
      },
      body: '{}'
    })
    .then(r => {
      element = document.querySelector(`.home-item[data-id="${item_id}"]`)
      element.remove()
    })
  }

  // window.onload = function() {
  //   status = document.getElementById('filter-bar')
  //   a = document.querySelector('#filter-bar input')
  //   console.log(a)
  //   endpoint = '{% url "api:items" %}' + `?approved=${status}`
  //   fetch(endpoint)
  //   .then(r => r.json())
  //   .then(data => {
  //     console.log(data)
  //   })
  // }
</script>
{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Login</h1>
  <form method="post">
    {% csrf_token %}
    <input type="text" name="username">
    <input type="password" name="password">
    <input type="submit" value="Submit">
  </form>

  <a href="{% url 'app:register' %}">Register</a>
</body>
</html>

app/templates/register.html
<h1>Register</h1>

<form method="post">
  {% csrf_token %}
  
  {{ form.as_p }}
  <input type="submit" value="Register">
</form>

app/templates/upload.html
{% extends 'base.html' %}
<!--  enctype="multipart/form-data" -->
{% block content %}
<form id="upload-form" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Upload">
</form>

<script>
  function uploadItem() {
    endpoint = "{% url 'api:items' %}"
    const form = document.getElementById('upload-form')

    fetch(endpoint, {
      method: 'POST',
      headers: {
        // 'Accept': 'application/json',
        'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryb0Ctt2zKN5yWNqDD',
        // 'Accept': 'multipart/form-data',
        //'X-CSRFToken': '{{ csrf_token }}'
      },
      body: new FormData(form)
    })
    .then(r => r.json())
    .then(data => {
      console.log(data)
    })
    .catch(error => {
        console.log('Error:', error);
        // Handle error
    })
  }
</script>
{% endblock %}

app/templates/upload_success.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ message }}</h1>
{% endblock %}